### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dr-harper**
### Checklist

I have:
- [ NA] brought the branch up to date with master,
- [ NA] added any relevant Github labels,
- [ NA] tested any new code,
- [X] added or updated any relevant documentation,
- [X] ensured all links in the documentation are correct,
- [X] updated the README, if relevant.

### Changes include
- [ ] Updates/fixes existing code
- [ ] Updates/fixes existing documentation
- [ ] Adds content for new indicators
- [ ] Other

### Description

Updates the README based on feedback from Linus

### CODE REVIEW

**Comment by traceyli** [comment]
The text has been changed so that it now addresses a 'general' audience, instead of a MNO audience as the original version did (note that the title of the repo is "resources for MNOs"). Please clarify the reason for this change, and who the 'general' audience is.

**Review by traceyli — COMMENTED** [review]
Please clarify why the text now addresses a 'general' audience instead of a MNO audience.
Please also make the writing style/tone consistent throughout, and correct the grammar.

**Comment by dr-harper** [comment]
Okay, we should check in with Linus in the morning. Valid comments!

**Comment by jc-harrison** [comment]
These changes have been superseded by other changes now on the master branch.

**Pull request closed without merging**
